trigger:
  - main

variables:
  buildConfiguration: "Release"
  serviceConnection: "az-serviceprincipal"
  resourceGroupDev: "rg-onecommerce-dev"
  resourceGroupProd: "rg-onecommerce-prod"

# BUILD

stages:
  - stage: Build
    displayName: Build & Tests
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: az-template/build-dotnet.yml
            parameters:
              buildConfiguration: $(buildConfiguration)
              projects:
                - name: OneFichiers
                  path: "**/OneFichiers.API/**/*.csproj"
                - name: OneCommandes
                  path: "**/OneCommandes.API/**/*.csproj"
                - name: OneFidelite
                  path: "**/OneFidelite.API/**/*.csproj"
                - name: OneProduit
                  path: "**/OneProduit.API/**/*.csproj"
                - name: OneCommerceMVC
                  path: "**/OneCommerce.MVC/**/*.csproj"

  # DEPLOY APIs DEV

  - stage: DeployApiDev
    displayName: Deploy APIs Dev OneCommerce
    dependsOn: Build
    jobs:
      - template: az-template/deploy-api.yml
        parameters:
          environment: Dev
          serviceConnection: $(serviceConnection)
          resourceGroup: $(resourceGroupDev)
          apps:
            - name: OneFichiers
            - name: OneCommandes
            - name: OneFidelite
            - name: OneProduit

  # DEPLOY MVC DEV

  - stage: DeployMvcDev
    displayName: Deploy MVC Dev OneCommerce
    dependsOn: DeployApiDev
    condition: succeeded()
    jobs:
      - template: az-template/deploy-mvc.yml
        parameters:
          environment: Dev
          serviceConnection: $(serviceConnection)
          resourceGroup: $(resourceGroupDev)
          appName: OneCommerceMVC

  # DEPLOY APIs PROD

  - stage: DeployApiProd
    displayName: Deploy APIs Prod OneCommerce
    dependsOn: DeployMvcDev
    condition: succeeded()
    jobs:
      - template: az-template/deploy-api.yml
        parameters:
          environment: Prod
          serviceConnection: $(serviceConnection)
          resourceGroup: $(resourceGroupProd)
          apps:
            - name: OneFichiers
            - name: OneCommandes
            - name: OneFidelite
            - name: OneProduit

  # DEPLOY MVC PROD

  - stage: DeployMvcProd
    displayName: Deploy MVC Prod OneCommerce
    dependsOn: DeployApiProd
    condition: succeeded()
    jobs:
      - template: az-template/deploy-mvc.yml
        parameters:
          environment: Prod
          serviceConnection: $(serviceConnection)
          resourceGroup: $(resourceGroupProd)
          appName: OneCommerceMVC
